# Generated by Django 3.2.5 on 2021-09-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('fantasy', 'Opowiadanie Fantasy'), ('erotic', 'Opowiadanie Erotyczne')], max_length=64)),
                ('plot', models.TextField()),
                ('publication_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
